
CC=gcc
CFLAGS=-Wall -Wextra -Werror
MYSQLCFLAGS= `mysql_config --cflags`
MYSQLLIBS= `mysql_config --libs`
INCLUDES= /usr/include/mysql/mysql.h

OBJS=Server.o Net.o File.o Mime.o Cache.o HashTable.o LinkedList.o Queue.o Mysql.o Api.o

all: Server

Server: $(OBJS)
	gcc -pthread -g -o $@ $(INCLUDES) $(MYSQLCFLAGS) $^ $(MYSQLLIBS)

Net.o: Net.c Net.h

Server.o: Server.c

File.o: File.c File.h

Mime.o: Mime.c Mime.h

Cache.o: Cache.c Cache.h

HashTable.o: HashTable.c HashTable.h

LinkedList.o: LinkedList.c LinkedList.h

Queue.o: Queue.c Queue.h

Mysql.o: Mysql.c Mysql.h

Api.o: Api.c Api.h

clean:
	rm -f $(OBJS)